- name: Setup Docker server
  hosts: web
  become: yes

  vars:
    app_directory: "/var/www/mywebapp"

  tasks:
    - name: Install Docker & Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Create app directory
      file:
        path: "{{ app_directory }}"
        state: directory

    - name: Clone repo
      git:
        repo: 'https://github.com/TONUTILISATEUR/TONPROJET.git'
        dest: "{{ app_directory }}"
        version: main

    - name: Launch Docker Compose
      shell: docker compose up -d --build
      args:
        chdir: "{{ app_directory }}"